#!/usr/bin/env lua
local fs = require("fs")

local args = {...}
if #args == 0 then
    args[1] = "."
end

local RESET = "\x1b[0m"
local GREEN = "\x1b[32m"
local RED = "\x1b[31m"

local function mbr(path)
    local bitrate = tonumber(
        io.popen(('ffprobe %q 2>&1'):format(path)):read("*a")
        :match("bitrate: (%d+)")
    )

    if bitrate then
        print(
            ('%s: %s%s%s kbps'):format(
                path,
                (bitrate < 192) and RED or GREEN,
                bitrate,
                RESET
            )
        )
    end
end

for _, path in ipairs(args) do
    local mode = fs.test(path)
    if mode == "file" then
        mbr(path)
    elseif mode == "dir" then
        for _,v in ipairs(fs.ls(path)) do
            mbr(fs.join(path, v))
        end
    else
        io.stderr:write(("mbr: no such file or dir: %s\n"):format(path))
    end
end
